### ISSUE TITLE
Incorrect redirect from https://godotengine.org/news to 404 page

### ISSUE THREAD

**Issue by devofnull** [godotengine/godot-website#528] opened 2023-01-17 14:23 UTC
https://godotengine.org/news should redirect to https://godotengine.org/blog/ as it did yesterday. Today it instead redirects to https://godotengine.org/https://godotengine.org/blog which leads to a 404 Page Not Found.

**Comment by devofnull** [comment] 2023-01-17 14:27
Sorry for duplicate, left bug report open before submitting and watched youtube. Other report came in during. Please feel free to delete in favor of older report.

**Comment by YuriSizov** [comment] 2023-01-17 14:41
Duplicate of https://github.com/godotengine/godot-website/issues/527.

**Closed as not planned by YuriSizov** 2023-01-17 14:41 UTC
Labels: bug, archived, topic:backend
